# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seedUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(609, 353)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 67, 17))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 191, 111))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 31, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 31, 17))
        self.label_3.setObjectName("label_3")
        self.txt_key = QtWidgets.QTextEdit(self.groupBox)
        self.txt_key.setGeometry(QtCore.QRect(50, 30, 131, 31))
        self.txt_key.setObjectName("txt_key")
        self.txt_key2 = QtWidgets.QTextEdit(self.groupBox)
        self.txt_key2.setGeometry(QtCore.QRect(50, 70, 131, 31))
        self.txt_key2.setObjectName("txt_key2")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 180, 191, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.combo_mode = QtWidgets.QComboBox(self.groupBox_2)
        self.combo_mode.setGeometry(QtCore.QRect(90, 50, 86, 25))
        self.combo_mode.setObjectName("combo_mode")
        self.combo_mode.addItem("")
        self.combo_mode.addItem("")
        self.combo_mode.addItem("")
        self.combo_mode.addItem("")
        self.combo_mode.addItem("")
        self.radio_encrypt = QtWidgets.QRadioButton(self.groupBox_2)
        self.radio_encrypt.setGeometry(QtCore.QRect(10, 30, 71, 23))
        self.radio_encrypt.setObjectName("radio_encrypt")
        self.radio_decrypt = QtWidgets.QRadioButton(self.groupBox_2)
        self.radio_decrypt.setGeometry(QtCore.QRect(10, 60, 71, 23))
        self.radio_decrypt.setObjectName("radio_decrypt")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(230, 70, 271, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(230, 90, 271, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(230, 110, 271, 17))
        self.label_6.setObjectName("label_6")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(230, 180, 351, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 61, 31))
        self.label_7.setObjectName("label_7")
        self.label_file = QtWidgets.QLabel(self.groupBox_3)
        self.label_file.setGeometry(QtCore.QRect(10, 70, 61, 31))
        self.label_file.setObjectName("label_file")
        self.txt_after_file = QtWidgets.QTextEdit(self.groupBox_3)
        self.txt_after_file.setGeometry(QtCore.QRect(80, 70, 161, 31))
        self.txt_after_file.setReadOnly(True)
        self.txt_after_file.setObjectName("txt_after_file")
        self.txt_before_file = QtWidgets.QTextEdit(self.groupBox_3)
        self.txt_before_file.setGeometry(QtCore.QRect(80, 30, 161, 31))
        self.txt_before_file.setReadOnly(True)
        self.txt_before_file.setObjectName("txt_before_file")
        self.btn_find_file = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_find_file.setGeometry(QtCore.QRect(250, 30, 89, 31))
        self.btn_find_file.setObjectName("btn_find_file")
        self.btn_play = QtWidgets.QPushButton(Dialog)
        self.btn_play.setGeometry(QtCore.QRect(390, 300, 89, 31))
        self.btn_play.setObjectName("btn_play")
        self.btn_finish = QtWidgets.QPushButton(Dialog)
        self.btn_finish.setGeometry(QtCore.QRect(490, 300, 89, 31))
        self.btn_finish.setObjectName("btn_finish")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "SEED"))
        self.groupBox.setTitle(_translate("Dialog", "키 설정"))
        self.label_2.setText(_translate("Dialog", "키"))
        self.label_3.setText(_translate("Dialog", "확인"))
        self.txt_key.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_2.setTitle(_translate("Dialog", "작업선택"))
        self.combo_mode.setItemText(0, _translate("Dialog", "CBC"))
        self.combo_mode.setItemText(1, _translate("Dialog", "CCM"))
        self.combo_mode.setItemText(2, _translate("Dialog", "CTR"))
        self.combo_mode.setItemText(3, _translate("Dialog", "ECB"))
        self.combo_mode.setItemText(4, _translate("Dialog", "GCM"))
        self.radio_encrypt.setText(_translate("Dialog", "암호화"))
        self.radio_decrypt.setText(_translate("Dialog", "복호화"))
        self.label_4.setText(_translate("Dialog", "암호화에 사용한 키(한글X)를 복호화에 사용합니다."))
        self.label_5.setText(_translate("Dialog", "키를 분실했을 경우 복구할 수 없습니다."))
        self.label_6.setText(_translate("Dialog", "사용에 주의를 부탁드립니다."))
        self.groupBox_3.setTitle(_translate("Dialog", "파일"))
        self.label_7.setText(_translate("Dialog", "원본파일"))
        self.label_file.setText(_translate("Dialog", "암호파일"))
        self.txt_after_file.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.txt_before_file.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_find_file.setText(_translate("Dialog", "파일찾기"))
        self.btn_play.setText(_translate("Dialog", "실행"))
        self.btn_finish.setText(_translate("Dialog", "종료"))
